---
title: "NYPD"
author: "siqi he"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r import, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(forecast)
library(leaflet)
library(leaflet.extras)
nypd <- read.csv("https://data.cityofnewyork.us/api/views/833y-fsy8/rows.csv?accessType=DOWNLOAD")

str(nypd)

head(nypd)

summary(nypd)
```


```{r race and sex, echo=FALSE}
nypd_pv_info <- nypd %>%
  select(INCIDENT_KEY, PERP_RACE, PERP_SEX, PERP_AGE_GROUP, VIC_RACE, VIC_SEX, VIC_AGE_GROUP) %>%
  rename(perpetrator_race = PERP_RACE,
         perpetrator_sex = PERP_SEX,
         perpetrator_age = PERP_AGE_GROUP,
         victim_race = VIC_RACE,
         victim_sex = VIC_SEX,
         victim_age = VIC_AGE_GROUP)

nypd_pv_info <- na.omit(nypd_pv_info)

```

```{r analyze, echo=FALSE}
nypd_pv_sex_counts <- nypd_pv_info %>%
  filter(!is.na(victim_sex) & !is.na(perpetrator_sex)) %>%
  mutate(sex_role = ifelse(victim_sex == perpetrator_sex, "Perpetrator", "Victim")) %>%
  group_by(sex_role, perpetrator_sex) %>%
  summarize(count = n()) %>% 
  ungroup()


# Create a bar chart of perpetrator sexes
ggplot(nypd_pv_sex_counts, aes(x = perpetrator_sex, y = count, fill = sex_role)) +
  geom_col(position = "dodge") +
  labs(x = "Sex", y = "Count", fill = "",
       title = "Distribution of Victim and Perpetrator Sexes") +
  scale_fill_manual(values = c("Victim" = "blue", "Perpetrator" = "red")) +
  theme(legend.position = "bottom")
```
```{r echo=FALSE}
nypd_pv_info_filtered <- nypd_pv_info %>% filter(!is.na(victim_age) & !is.na(perpetrator_age))

# Create a data frame for the histogram
hist_data <- data.frame(
  age = c(nypd_pv_info_filtered$victim_age, nypd_pv_info_filtered$perpetrator_age),
  group = factor(rep(c("Victim", "Perpetrator"), c(nrow(nypd_pv_info_filtered), nrow(nypd_pv_info_filtered))))
)

# Create a histogram of age for both victims and perpetrators
ggplot(hist_data, aes(x = age, fill = group)) +
  geom_bar(position = "dodge") +
  scale_fill_manual(values = c("blue", "red")) +
  labs(title = "Age Distribution of Victims and Perpetrators", x = "Age", y = "Frequency")
```

```{r echo=FALSE}
nypd_pv_race_counts <- nypd_pv_info %>%
  drop_na(victim_race, perpetrator_race) %>%
  group_by(victim_race, perpetrator_race) %>%
  summarize(count = n())
ggplot(nypd_pv_race_counts, aes(x = victim_race, y = perpetrator_race, fill = count)) +
  geom_point(shape = 21, size = 8) +
  scale_fill_gradient(low = "white", high = "red") +
  labs(x = "Victim Race", y = "Perpetrator Race", fill = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(panel.grid.major = element_line(color = "gray80", size = 0.2),
        panel.grid.minor = element_blank())

```

```{r echo=FALSE}
nypd_date <- nypd %>% filter(!is.na(OCCUR_DATE))

nypd_date$year <- as.numeric(format(as.Date(nypd_date$OCCUR_DATE, "%m/%d/%Y"), "%Y"))
nypd_date$month <- as.numeric(format(as.Date(nypd_date$OCCUR_DATE, "%m/%d/%Y"), "%m"))

nypd_monthly_counts <- nypd_date %>% group_by(year, month) %>% summarize(count = n())

n_colors <- length(unique(nypd_monthly_counts$year))
color_palette <- rainbow(n_colors)

ggplot(nypd_monthly_counts, aes(x = month, y = count, group = year, color = as.factor(year))) +
  geom_line() +
  scale_color_manual(values = color_palette) +
  labs(title = "Monthly Crime Incidents per Year", x = "Month", y = "Incident Count")
```
```{r forcast, echo=FALSE}

ts_counts <- ts(nypd_monthly_counts$count, start = c(min(nypd_monthly_counts$year), min(nypd_monthly_counts$month)), frequency = 12)

# Fit an ARIMA model to the time series
arima_model <- auto.arima(ts_counts)

# Forecast the next 12 months and plot the results
forecast_values <- forecast(arima_model, h = 12)

# Extract the forecast for the next year
nypd_forecast <- data.frame(year = rep(max(nypd_monthly_counts$year) + 1, 12),
                            month = 1:12,
                            count = forecast_values$mean)

# Plot the forecast for the next year
ggplot(nypd_forecast, aes(x = month, y = count, group = year, color = as.factor(year))) +
  geom_line() +
  scale_color_manual(values = color_palette) +
  labs(title = "Forecast of Monthly Crime Incidents for Next Year", x = "Month", y = "Incident Count")
```

```{r model, echo=FALSE}
nypd_date <- nypd %>% filter(!is.na(OCCUR_DATE) & !is.na(OCCUR_TIME))

nypd_date$year <- as.numeric(format(as.Date(nypd_date$OCCUR_DATE, "%m/%d/%Y"), "%Y"))
nypd_date$hour <- as.numeric(substr(nypd_date$OCCUR_TIME, 1, 2))

nypd_hourly_counts <- nypd_date %>% group_by(year, hour) %>% summarize(count = n())

n_colors <- length(unique(nypd_hourly_counts$year))
color_palette <- rainbow(n_colors)

ggplot(nypd_hourly_counts, aes(x = hour, y = count, group = year, color = as.factor(year))) +
  geom_line() +
  scale_color_manual(values = color_palette) +
  labs(title = "Hourly Crime Incidents per Year", x = "Hour of the Day", y = "Incident Count")


```

```{r echo=FALSE}

nypd_loc <- nypd %>% 
  filter(!is.na(PRECINCT) & !is.na(BORO) & !is.na(Longitude) & !is.na(Latitude)) %>%
  select(Precinct = PRECINCT, borough = BORO, Longitude, Latitude)
nypd_loc %>% 
  leaflet() %>%
  addTiles()%>%
  fitBounds(max(nypd_loc$Longitude), 
            min(nypd_loc$Latitude), 
            min(nypd_loc$Longitude), 
            max(nypd_loc$Latitude)) %>% 
  addHeatmap(lng=nypd_loc$Longitude, 
             lat=nypd_loc$Latitude, 
             blur=30, 
             radius=15)
```

